name: Build and Release Resume

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nebriv/docker-lualatex:master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build resume
        run: lualatex resume.tex

      - name: Upload resume.pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: resume.pdf

  release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Extract branch and tag info
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        id: extract_info

      - name: Download resume.pdf
        uses: actions/download-artifact@v2
        with:
          name: resume.pdf
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: resume-${{ steps.extract_info.outputs.branch }}-${{ steps.extract_info.outputs.tag }}
          artifacts: "./resume.pdf"
          body: "Release of the updated resume"
          token: ${{ secrets.GITHUB_TOKEN }}

