name: Build, Tag, and Release Resume

on:
  push:
    branches: 
      - '**'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: bump_version
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: "resume-${{ github.ref_name }}-"
          release_branches: ".*"
          
  build:
    needs: bump_version
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nebriv/docker-lualatex:master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build resume
        run: lualatex resume.tex

      - name: Upload resume.pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: resume.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download resume.pdf
        uses: actions/download-artifact@v2
        with:
          name: resume.pdf
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.bump_version.outputs.new_tag }}
          artifacts: "./resume.pdf"
          body: "Release of the updated resume"
          token: ${{ secrets.GITHUB_TOKEN }}
