name: Build, Tag, and Release Resume

on:
  push:
    branches: 
      - '**'

jobs:
  build_tag_release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nebriv/docker-lualatex:master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: "resume-${{ github.ref_name }}-"
          release_branches: ".*"

      - name: Build resume
        run: lualatex resume.tex

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump_version.outputs.new_tag }}
          artifacts: "./resume.pdf"
          body: "Release of the updated resume"
          token: ${{ secrets.GITHUB_TOKEN }}
