name: Build and Release Resume

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to master branch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nebriv/docker-lualatex:master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build resume
        run: lualatex resume.tex

      - name: Upload resume.pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: resume.pdf

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download resume.pdf
        uses: actions/download-artifact@v2
        with:
          name: resume.pdf
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./resume.pdf"
          body: "Release of the updated resume"
          token: ${{ secrets.GITHUB_TOKEN }}

